### ISSUE TITLE
how to use it , how to install

### ISSUE THREAD

**Issue by akshaynikhare** [CreativeDesigner3D/Library_CAD_Drawings#1]
Hi Andrew ,
can you explain me how we can use it.

**Comment by CreativeDesigner3D** [comment]
This is in the very early stages of development. It will likely be several more weeks before it is ready. I will release information about this library as soon as possible.

**Comment by akshaynikhare** [comment]
hey Andrew ,
I am furniture designer & a software engineer , i really like the project , i want to develop it , do you have discord server or something where we can chat .

i can help build some feature .

**Comment by CreativeDesigner3D** [comment]
Thanks for reaching out. Here is the discord link. 

Discord – https://discord.gg/yxZSbtJFkw
